# Generated by Django 4.0.4 on 2022-05-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('genderM', models.BooleanField(default=True)),
                ('date_of_birth', models.DateField()),
                ('level', models.IntegerField()),
                ('gpa', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
