# Generated by Django 4.0.4 on 2022-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='genderM',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
