# Generated by Django 4.0.4 on 2022-05-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
